# Site settings
title: buckhx
baseurl: "/"
url: "http://github.com/buckhx"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
